[env:seeeduino_xiao_esp32s3]
platform = espressif32
board = seeeduino_xiao_esp32s3
framework = arduino
monitor_speed = 115200

# Libraries
lib_deps = 
    bluedroid
    esp32-a2dp
    adafruit/Adafruit MAX98357 I2S Class D Mono Amp
    
# Build flags
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

# Serial port (adjust if needed)
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
